Repository pmz-q/est_wassup_02, pull requests merged in 2024-01, with the labels that each got.

#11 #7 merging multiple csv files into one
  .gitignore
  data/features/.gitkeep
  data/origin/test/.gitkeep
  data/origin/train/.gitkeep
  examinations/.gitkeep
  preprocess/merge_data.ipynb
  preprocess/merge_data.py
Labels: new-feature, eda

#22 Dev 18
  .gitignore
  code/arima.py
  code/config.py
  code/models.py
  code/train.py
  code/utils.py
  configs/arima_config.py
  configs/preprocess_config.py
  configs/train_config.py
  core/dataloader/__init__.py
  core/dataloader/patch_tst_dataset.py
  core/dataloader/time_series_dataset.py
  core/metrics/__init__.py
  core/metrics/mae.py
  core/metrics/mape.py
  core/metrics/r2_score.py
  core/preprocess/__init__.py
  core/preprocess/custom_dataset.py
  core/preprocess/origin_dataset.py
  core/preprocess/utils/__init__.py
  core/preprocess/utils/merge/__init__.py
  core/preprocess/utils/merge/merge_client.py
  core/preprocess/utils/merge/merge_electricity_prices.py
  core/preprocess/utils/merge/merge_forecast_weather.py
  core/preprocess/utils/merge/merge_gas_prices.py
  core/preprocess/utils/merge/merge_historical_weather.py
  core/preprocess/utils/merge/tools.py
  core/preprocess/utils/merge_dataset.py
  core/trains/__init__.py
  core/trains/arima.py
  core/trains/nn_train.py
  core/trains/nn_validate.py
  core/utils/__init__.py
  core/utils/arg_parsers.py
  core/utils/file_handler.py
  core/utils/preprocess_tools.py
  data/origin/test/.gitkeep
  data/origin/train/.gitkeep
  data/test/.gitkeep
  data/train/.gitkeep
  examinations/data_overlook.ipynb
  examinations/merge_data/merge_data.ipynb
  examinations/merge_data/merge_data.py
  models/__init__.py
  models/ann.py
  models/patch_tst.py
  output/model_output/240104_01.pth
  output/model_output/model.pth
  output/results/240104_01.png
  preprocess.py
  requirements.txt
  train.py
  train_arima.py
Labels: feature-update

#23 Dev 19 - ARIMA and EDA with merged dataset
  examinations/after_merge_arima.ipynb
  examinations/after_merge_eda.ipynb
  examinations/revealed_target.ipynb
Labels: documentation, eda

#30 Dev 26
  configs/arima_config.py
  configs/preprocess_config.py
  configs/train_config.py
  core/dataloader/time_series_dataset.py
  core/preprocess/custom_dataset.py
  core/trains/nn_train.py
  core/trains/nn_validate.py
  examinations/after_merge_arima.ipynb
  examinations/merge_data/merge_data.py
  models/ann.py
  train.py
  train_arima.py
Labels: bug-fix

#35 Dev 28
  configs/patchtst_config.py
  configs/preprocess_config.py
  core/dataloader/patch_tst_dataset.py
  core/preprocess/custom_dataset.py
  core/trains/tst_train.py
  core/trains/tst_validate.py
  core/utils/arg_parsers.py
  models/patch_tst.py
  preprocess.py
  train_patchtst.py
Labels: new-feature

#34 Dev 32
  configs/train_config.py
  core/dataloader/time_series_dataset.py
  core/preprocess/custom_dataset.py
  core/trains/__init__.py
  core/trains/nn_predict.py
  core/trains/nn_train.py
  core/trains/nn_validate.py
  core/utils/preprocess_tools.py
  models/ann.py
  train.py
Labels: bug-fix, new-feature, feature-update

#38 Dev 37
  configs/patchtst_config.py
  configs/preprocess_config.py
  configs/train_config.py
  core/preprocess/custom_dataset.py
  core/trains/__init__.py
  core/trains/tst_predict.py
  core/trains/tst_train.py
  core/trains/tst_validate.py
  models/ann.py
  models/patch_tst.py
  train.py
  train_patchtst.py
Labels: bug-fix, feature-update

#39 Dev 36
  configs/preprocess_config.py
  core/preprocess/custom_dataset.py
  core/utils/preprocess_tools.py
Labels: feature-update, eda

#41 added: add holidays feature
  configs/preprocess_config.py
  core/preprocess/utils/merge/__init__.py
  core/preprocess/utils/merge/merge_holidays.py
  core/preprocess/utils/merge_dataset.py
  requirements.txt
Labels: new-feature, eda

#43 added: auto-train
  .gitignore
  auto-configs-arima/.gitkeep
  auto-configs-nn/.gitkeep
  auto-configs-tst/.gitkeep
  auto_train.py
  configs/arima_config.py
  configs/patchtst_config.py
  configs/train_config.py
  core/utils/__init__.py
  core/utils/file_handler.py
  train.py
  train_arima.py
  train_patchtst.py
Labels: new-feature

#46 hot-fix: create_path_if_not_exists: create_new_path 인자 추가
  core/utils/file_handler.py
  preprocess.py
Labels: bug-fix

#47 hot-fix: create_path_if_not_exists: create_new_path 인자 추가
  core/utils/file_handler.py
  preprocess.py
Labels: bug-fix

#48 hot-fix: arima set_index error
  core/preprocess/custom_dataset.py
Labels: bug-fix

#50 Dev 49
  .gitignore
  configs/arima_config.py
  core/trains/arima.py
  core/utils/file_handler.py
  train_arima.py
Labels: bug-fix

#51 Dev
  .gitignore
  configs/arima_config.py
  core/trains/arima.py
  core/utils/file_handler.py
  train_arima.py
Labels: bug-fix

#52 edited: auto-train 실행 시, 파일명 표시
  auto_train.py
Labels: feature-update

#54 hot-fix: create_path_if_not_exists returns new path
  core/utils/file_handler.py
Labels: bug-fix

#55 Dev 53
  configs/patchtst_config.py
  configs/train_config.py
  core/trains/nn_train.py
  core/trains/tst_train.py
  core/utils/__init__.py
  core/utils/save_best_model.py
  models/__init__.py
  train.py
  train_patchtst.py
Labels: new-feature

#56 Dev
  configs/patchtst_config.py
  configs/train_config.py
  core/trains/nn_train.py
  core/trains/tst_train.py
  core/utils/__init__.py
  core/utils/save_best_model.py
  models/__init__.py
  train.py
  train_patchtst.py
Labels: new-feature

#58 Dev: hot-fix: when no scalse errors: nn&tst
  core/utils/__init__.py
  core/utils/file_handler.py
  preprocess.py
  train.py
  train_patchtst.py
Labels: bug-fix

#59 hot-fix: requirements.txt & encoding parser error for window setups
  auto_train.py
  requirements.txt
  train.py
  train_patchtst.py
Labels: bug-fix

#60 hot-fix: early-stopping logic error
  core/trains/nn_train.py
  core/trains/tst_train.py
Labels: bug-fix

#62 README version 1
  .gitignore
  README.md
  blobs/origin-data-structure.png
Labels: documentation

#63 readme version 1
  .gitignore
  README.md
  blobs/origin-data-structure.png
Labels: documentation

#64 hot-fix: x-scaler only config available
  core/preprocess/custom_dataset.py
Labels: bug-fix

#66 Dev 61
  .gitignore
  README.md
  configs/preprocess_config.py
  user-guide-eng.ipynb
  user-guide-kor.ipynb
Labels: bug-fix

#67 Dev
  .gitignore
  README.md
  configs/preprocess_config.py
  user-guide-eng.ipynb
  user-guide-kor.ipynb
Labels: documentation

#68 added: train.py: random seed
  train.py
  train_patchtst.py
Labels: bug-fix
